require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # ItemComment. As you add validations to ItemComment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemCommentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all item_comments as @item_comments" do
      item_comment = ItemComment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:item_comments).should eq([item_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested item_comment as @item_comment" do
      item_comment = ItemComment.create! valid_attributes
      get :show, {:id => item_comment.to_param}, valid_session
      assigns(:item_comment).should eq(item_comment)
    end
  end

  describe "GET new" do
    it "assigns a new item_comment as @item_comment" do
      get :new, {}, valid_session
      assigns(:item_comment).should be_a_new(ItemComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested item_comment as @item_comment" do
      item_comment = ItemComment.create! valid_attributes
      get :edit, {:id => item_comment.to_param}, valid_session
      assigns(:item_comment).should eq(item_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemComment" do
        expect {
          post :create, {:item_comment => valid_attributes}, valid_session
        }.to change(ItemComment, :count).by(1)
      end

      it "assigns a newly created item_comment as @item_comment" do
        post :create, {:item_comment => valid_attributes}, valid_session
        assigns(:item_comment).should be_a(ItemComment)
        assigns(:item_comment).should be_persisted
      end

      it "redirects to the created item_comment" do
        post :create, {:item_comment => valid_attributes}, valid_session
        response.should redirect_to(ItemComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved item_comment as @item_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemComment.any_instance.stub(:save).and_return(false)
        post :create, {:item_comment => {}}, valid_session
        assigns(:item_comment).should be_a_new(ItemComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemComment.any_instance.stub(:save).and_return(false)
        post :create, {:item_comment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested item_comment" do
        item_comment = ItemComment.create! valid_attributes
        # Assuming there are no other item_comments in the database, this
        # specifies that the ItemComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemComment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => item_comment.to_param, :item_comment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested item_comment as @item_comment" do
        item_comment = ItemComment.create! valid_attributes
        put :update, {:id => item_comment.to_param, :item_comment => valid_attributes}, valid_session
        assigns(:item_comment).should eq(item_comment)
      end

      it "redirects to the item_comment" do
        item_comment = ItemComment.create! valid_attributes
        put :update, {:id => item_comment.to_param, :item_comment => valid_attributes}, valid_session
        response.should redirect_to(item_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the item_comment as @item_comment" do
        item_comment = ItemComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_comment.to_param, :item_comment => {}}, valid_session
        assigns(:item_comment).should eq(item_comment)
      end

      it "re-renders the 'edit' template" do
        item_comment = ItemComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_comment.to_param, :item_comment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested item_comment" do
      item_comment = ItemComment.create! valid_attributes
      expect {
        delete :destroy, {:id => item_comment.to_param}, valid_session
      }.to change(ItemComment, :count).by(-1)
    end

    it "redirects to the item_comments list" do
      item_comment = ItemComment.create! valid_attributes
      delete :destroy, {:id => item_comment.to_param}, valid_session
      response.should redirect_to(item_comments_url)
    end
  end

end
